### ISSUE TITLE
animated underline

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-input#41] opened 2015-07-10 17:16 UTC
I noticed that the underline stopped animating. is this a regression?
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html

**Comment by LM450N** [comment] 2015-07-10 18:50
I think it's by design, no ? If you type a number into the first demo of Validation, the underline is animated.

**Comment by notwaldorf** [comment] 2015-07-13 19:19
The underline comes from `paper-input`, not `iron-input`, and I think it's been fixed in the latest release.

**Comment by notwaldorf** [comment] 2015-08-17 21:24
No longer reproducible

**Closed by notwaldorf** 2015-08-17 21:24 UTC
Labels: bug
