### ISSUE TITLE
iron-input should implement IronFormElementBehavior

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/iron-input#63] opened 2015-11-19 13:27 UTC
`<input is="iron-input"...>` doesn't implement IronFormElementBehavior and isn't registered by iron-form as a custom elements and iron-form's validate() assumes the extended native element should have already been validated. 

Ref: [issue](https://github.com/PolymerElements/iron-form/issues/86).

**Comment by notwaldorf** [comment] 2016-01-05 19:39
For repro steps, here's a jsbin with this issue: http://jsbin.com/zadoje/edit?html,output.

I think the solution isn't to add `IronFormElementBehaviour` to this (as explained in https://github.com/PolymerElements/iron-input/issues/64 this will double submit inputs), but to have iron-form do the right thing (i.e. look through the `form.elements` array and see which ones are custom elements`).

I will take a look this week.

**Comment by notwaldorf** [comment] 2016-01-28 21:03
Closing, as this isn't the right fix for the element (the issue is in `iron-form`)

**Closed** 2016-01-28 21:03 UTC
